data:
  H: 64 #40
  W: 64 #40
  channels: 3 #3

training:
  n_epochs: 200
  batch_size: 64
  optimization:
    optimizer_name: Adam # which optimizer to use during training
    Adam:
      betas:
        - 0.9
        - 0.999
      lr: 0.001
    SGD:
      momentum: 0.9
      lr: 0.001

VAE:
  D: 128 # dimensionality of the latent space

DDPM:
  T: 500