data:
  H: 64 #40
  W: 64 #40
  channels: 3 #3
  n_classes: 18

training:
  n_epochs: 600 # ! Overwritten by the model specific config
  batch_size: 24 # ! Overwritten by the model specific config
  optimization:
    optimizer_name: Adam # which optimizer to use during training
    Adam:
      betas:
        - 0.9
        - 0.999
      lr: 0.001
    SGD:
      momentum: 0.9
      lr: 0.001

VAE:
  n_epochs: 600
  batch_size: 64
  D: 128 # dimensionality of the latent space
  num_components: 10 # ! Only for MoG and VampPrior

DDPM:
  n_epochs: 600
  batch_size: 24
  T: 500
  p_uncond: 0.1